# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Logintodockerhub:
    runs-on: ubuntu-latest
    environment: Pruthvi-Env
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERUSERPASSWORD}}
      - name: Docker pull
        run: docker pull mysql
      - name: docker tag
        run: docker tag mysql pruthvi2397/docker-repo
      - name: docker push 
        run: docker push pruthvi2397/docker-repo

  Logintodockerhub2:
    runs-on: ubuntu-latest
    environment: Pruthvi-Env2
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        uses: docker/login-action@v2.1.0
        with:
          registry: registry-1.docker.io
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERUSERPASSWORD}}
