# This is a basic workflow to help you get started with Actions
 
name: Login docker hub
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Logintodockerhub:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERUSERPASSWORD}}
          run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} registry.hub.docker.com
      - name: Docker pull
        run: docker pull mysql
      - name: docker tag
        run: docker tag mysql pruthvi2397/docker-repo
      - name: docker push 
        run: docker push pruthvi2397/docker-repo
  Logintodockerhub2:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERUSERPASSWORD}}
